# site name
prefixName: CPU
siteName: Tern
# favicon and site master avatar
favicon: /images/favicon.png
cdn: https://cdn.jsdelivr.net/gh/TernYoung/nicePicture
avatar: /icon/favicon.png
url: www.cputern.top
description: Shit Happens But Life Goes On
#cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
pjax: 1
# 1开启
# MathJax Support
mathjax: 1

notice: 学更多的东西！
lazyloadImg: https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/icon/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book },
    资源: {path: /categories/资源/, fa: fa-cloud-download }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人链: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
#客户端: { path: /client/, fa: fa-android faa-vertical }
#RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic001.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic002.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic003.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic004.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic005.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic015.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic007.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic008.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic009.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic010.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic015.png
  - https://cdn.jsdelivr.net/gh/TernYoung/nicePicture/largePic/png/pic022.png

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /smallPic/pic001.jpg}
  - {url: /, title: Tern的万事屋, desc: 技术服务, img: /smallPic/pic001.jpg}


# your site build time or founded date
siteBuildingTime: 07/17/2019

#social  url, img PC端配置
social:
  github: {url: http://github.com/TernYoung, img: /icon/social/github.png}
#sina: {url: http://weibo.com/mashirozx?is_all=1, img: /icon/social/sina.png}
#wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /icon/social/wangyiyun.png}
#zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /icon/social/zhihu.png}
#email: {url: http://weibo.com/mashirozx?is_all=1, img: /icon/social/email.svg}
  wechat: {url: /#, qrcode: /contact/weChat.jpg, img: /icon/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/TernYoung, fa: fa-github, color: 333}
#weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=&site=975429539&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
#paypal: https://www.paypal.me/hojuncn
  alipay: /contact/alipay.jpg
  wechat: /contact/wechatpay.jpg
  wechatSQ: /contact/wechatpay.jpg

#视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 3050357673
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: CamBhb9zezGsaY1N4Xflnmol-gzGzoHsz
v_appKey: pwG2i33AWjwOOQnEPqLwuW62

#百度统计
baidu_tongji:
  enable: true
  sitecode:  8ed631e35fec02d0275a0fec8cd93734
